#!/bin/bash

# Make vim the default editor
export EDITOR="vim"
# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Norwegian numbers and stuff
export LC_ALL="nb_NO.UTF-8";
# US English for language
export LANG="en_US.UTF-8";
export LANGUAGE="en_US.UTF-8";
export LC_CTYPE="en_US.UTF-8";
export LC_COLLATE="en_US.UTF-8";
export LC_MESSAGES="en_US.UTF-8";

# PATH like a bawss
PATH=$PATH:/usr/local/bin
PATH=$PATH:$HOME/.local/bin

export PATH

export CDPATH=.:$HOME:$HOME/Projects:$HOME/NRK

export BAT_THEME="Dracula"
