#!/bin/bash

## Command history configuration
if [ -z "$HISTFILE" ]; then
    HISTFILE=$HOME/.zsh_history
fi

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export SAVEHIST=1000
export HISTORY_IGNORE="(c|ls|cd|cd -|pwd|exit|* --help|* -h|git s|git lg|git p|git f|git r|tig|sudo reboot now|ranger|atom|tre|..|...|....|repo|cal|la|top)";

# Show history
case $HIST_STAMPS in
  "mm/dd/yyyy") alias history='fc -fl 1' ;;
  "dd.mm.yyyy") alias history='fc -El 1' ;;
  "yyyy-mm-dd") alias history='fc -il 1' ;;
  *) alias history='fc -l 1' ;;
esac

# If this is set, zsh sessions will append their history list to the history file, rather than replace it. Thus, multiple parallel zsh sessions will all have the new entries from their history lists added to the history file, in the order that they exit. The file will still be periodically re-written to trim it when the number of lines grows 20% beyond the value specified by $SAVEHIST (see also the HIST_SAVE_BY_COPY option).
setopt append_history
# Save each command’s beginning timestamp (in seconds since the epoch) and the duration (in seconds) to the history file.
setopt extended_history
# If the internal history needs to be trimmed to add the current command line, setting this option will cause the oldest history event that has a duplicate to be lost before losing a unique event from the list.
setopt hist_expire_dups_first
# Do not enter command lines into the history list if they are duplicates of the previous event.
setopt hist_ignore_dups
# Remove command lines from the history list when the first character on the line is a space, or when one of the expanded aliases contains a leading space.
setopt hist_ignore_space
# Whenever the user enters a line with history expansion, don’t execute the line directly; instead, perform history expansion and reload the line into the editing buffer.
setopt hist_verify
# This options works like APPEND_HISTORY except that new history lines are added to the $HISTFILE incrementally (as soon as they are entered), rather than waiting until the shell exits.
setopt inc_append_history
