#!/bin/bash

# Easier navigation: .., ...
alias ..="cd .."
alias cd..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# List all files colorized in long format
alias l="ls"

# List all files colorized in long format, including dot files
alias la="exa -lh --git --git-ignore"

# List only directories
alias lsd='exa -D'

alias ls="exa"

alias c="clear"

# Get the currect week number
alias week="date +%-V"

# Make both cp and mv interactive by default
alias mv="mv -i"
alias cp="cp -i"

# Pipe my public key to my clipboard.
alias pubkey="gpg --export --armor"

# Sane cal
alias cal="ncal -bM3"

# Give me a calculator when I want a calculator
alias calc="eva"
