#!/bin/bash

# Easier navigation: .., ...
alias ..="cd .."
alias cd..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# List all files colorized in long format
alias l="ls -l --color"

# List all files colorized in long format, including dot files
alias la="ls -la --color"

# List only directories
alias lsd='ls -l | grep "^d"'

alias ls="command ls --color"

alias c="clear"

# Get the currect week number
alias week="date +%-V"

# Make both cp and mv interactive by default
alias mv="mv -i"
alias cp="cp -i"

# Pipe my public key to my clipboard.
alias pubkey="gpg --export --armor"
