#!/bin/bash

# Make vim the default editor
export EDITOR="vim"
# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Norwegian numbers and stuff
export LC_ALL="nb_NO.UTF-8";
# US English for language
export LANG="en_US.UTF-8";
export LANGUAGE="en_US.UTF-8";
export LC_CTYPE="en_US.UTF-8";
export LC_COLLATE="en_US.UTF-8";
export LC_MESSAGES="en_US.UTF-8";

# PATH like a bawss
PATH=$PATH:/usr/local/bin
PATH=$PATH:$HOME/local/bin
PATH=$PATH:$HOME/bin

export PATH

export CDPATH=.:$HOME:$HOME/projects:$HOME/nrk

# Used for i3 volume controls
export AMIXER_SOUND_CARD=0
export AMIXER_SOUND_CONTROL="Master,0"

# GPG stuff:

# If the socket we want to use cannot be found, then create it
# This lets us create multiple shells without haivng to juggle things
if [[ -S "$( gpgconf --list-dirs agent-ssh-socket )" ]]; then
  SSH_AUTH_SOCK=$( gpgconf --list-dirs agent-ssh-socket );
  export SSH_AUTH_SOCK;
else
  eval "$( gpg-agent --daemon --enable-ssh-support )";
fi

GPG_TTY=$(tty)
export GPG_TTY

export BAT_THEME="Dracula"
